### ISSUE TITLE
Remove Sunlight Foundation branding

### ISSUE THREAD

**Issue by jpmckinney** [sunlightlabs/lapidus#7]
Assuming you want this project to see significant re-use, it may be a good idea to remove Sunlight's branding from `base.html`

**Comment by dcloud** [comment]
Ultimately I'd like to pull that info out, but I see it as possible part of a larger CMS-ification of the dashboard app. Providing this through template snippets or some sitedata models similar to the approach of many django-based CMSs. Or maybe move those templates to a projects folder similar to pinax's [project dirs](https://github.com/pinax/pinax/tree/master/pinax/projects)?

**Comment by andybak** [comment]
Just to add my thoughts. I'd be interested in using Lapidus as a pluggable app especially if it integrated into the normal admin. I was a little put off by the monolithic nature of the project as it stands.
